from . import student
from . import teacher
from . import course
from . import class_room
from . import enrollment
from . import attendance
from . import exam
from . import grade
from . import fee
from . import timetable
